//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDD_Major_Work.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Book9780241558300 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Book9780241558300"]));
            }
            set {
                this["Book9780241558300"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Available")]
        public string Book9780241558324 {
            get {
                return ((string)(this["Book9780241558324"]));
            }
            set {
                this["Book9780241558324"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Available")]
        public string Book9780241558348 {
            get {
                return ((string)(this["Book9780241558348"]));
            }
            set {
                this["Book9780241558348"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Available")]
        public string Book9780241558331 {
            get {
                return ((string)(this["Book9780241558331"]));
            }
            set {
                this["Book9780241558331"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Available")]
        public string Book9780241558355 {
            get {
                return ((string)(this["Book9780241558355"]));
            }
            set {
                this["Book9780241558355"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Available")]
        public string Book9780241578186 {
            get {
                return ((string)(this["Book9780241578186"]));
            }
            set {
                this["Book9780241578186"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Available")]
        public string Book9780241558485 {
            get {
                return ((string)(this["Book9780241558485"]));
            }
            set {
                this["Book9780241558485"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Available")]
        public string Book9780141322681 {
            get {
                return ((string)(this["Book9780141322681"]));
            }
            set {
                this["Book9780141322681"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Available")]
        public string Book9780140375336 {
            get {
                return ((string)(this["Book9780140375336"]));
            }
            set {
                this["Book9780140375336"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Available")]
        public string Book9780241568644 {
            get {
                return ((string)(this["Book9780241568644"]));
            }
            set {
                this["Book9780241568644"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Available")]
        public string Book9780141346496 {
            get {
                return ((string)(this["Book9780141346496"]));
            }
            set {
                this["Book9780141346496"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Available")]
        public string Book9780241558508 {
            get {
                return ((string)(this["Book9780241558508"]));
            }
            set {
                this["Book9780241558508"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Available")]
        public string Book9780241578179 {
            get {
                return ((string)(this["Book9780241578179"]));
            }
            set {
                this["Book9780241578179"] = value;
            }
        }
    }
}
